name: wiatag_kit
description: "A new Flutter plugin project."
version: 1.0.0
repository: https://github.com/goldenm-software/wiatag_kit
homepage: https://developers.layrz.com/components/dart-flutter/wiatag_kit


environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: com.layrz.wiatag_kit
        pluginClass: WiatagKitPlugin
      ios:
        pluginClass: WiatagKitPlugin
