name: Publish to pub.dev

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/flutter-web-builder:flutter3.19.3-python3.11
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    env:
      PUB_JSON: ${{ secrets.LAYRZ_PUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        run: |
          python3 authenticate.py
      
      - name: Publish
        run: |
          flutter pub publish --force
      
      - name: Cleanup
        run: |
          dart pub token remove https://pub.dev

